config/routes.rb
Rails.application.routes.draw do
  get 'search/index'
  post 'search', to: 'search#search', as: :search
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "search#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :genre
    belongs_to :author
    belongs_to :publisher

    searchkick text_middle: [:title, :content, :author_name, :genre_name, :publisher_name]

    def search_data
        attributes.merge(
            genre_name: genre.name,
            author_name: author.name,
            publisher_name: publisher.name
    )
    end
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/publisher.rb
class Publisher < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def current_user
        user = User.find_by(ip_address: request.remote_ip)
        return user.present? ? user :  User.create(ip_address: request.remote_ip) 
    end    
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index 
    @recomendations = current_user.recomendation.nil? ? [] :
    Book.where(
      "#{current_user.recomendation_type}": 
      current_user.recomendation_type.classify.constantize.find_by(name: current_user.recomendation)
    )
  end

  def search
    @books = Book.search(params[:search], operator: 'or')
    @recomendations = @books.length > 0 ? analytics : []
    puts "recomendations: #{@recomendations[0]}"
    render turbo_stream: [
      turbo_stream.update('books', partial: 'results', locals: {books: @books }),
      turbo_stream.update('recomendations', partial: 'recomendations',
      locals: {recomendations: @recomendations })
    ] 
  end
  
  def analytics
    genres = {}
    max_genre = []
    publishers = {}
    max_publisher =  []
    authors = {}
    max_author = []
    
    @books.includes(:genre, :publisher, :author).each do |book|

      genres["#{book.genre.name}"] = genres["#{book.genre.name}"].nil? ? 
      { ids: [book.id], repeat: 1 } 
      :
      { ids: genres["#{book.genre.name}"][:ids].push(book.id) , 
      repeat: genres["#{book.genre.name}"][:repeat] + 1 }

      max_genre[genres["#{book.genre.name}"][:repeat]] = book.genre

      publishers["#{book.publisher.name}"] = publishers["#{book.publisher.name}"].nil? ? 
      { ids: [book.id], repeat: 1 } 
      :
      { ids: publishers["#{book.publisher.name}"][:ids].push(book.id) ,
      repeat: publishers["#{book.publisher.name}"][:repeat] + 1 }

      max_publisher[publishers["#{book.publisher.name}"][:repeat]] = book.publisher

      authors["#{book.author.name}"] = authors["#{book.author.name}"].nil? ? 
      { ids: [book.id], repeat: 1 } 
      :
      { ids: authors["#{book.author.name}"][:ids].push(book.id) ,
      repeat: authors["#{book.author.name}"][:repeat] + 1 }

      max_author[authors["#{book.author.name}"][:repeat]] = book.author
    end

    author = max_author[max_author.length - 1]
    genre = max_genre[max_genre.length - 1]
    publisher = max_publisher[max_publisher.length - 1]

    author_books = Book.where(author: author).
    where.not(id: authors["#{author.name}"][:ids])

    genre_books = Book.where(genre: genre).
    where.not(id: genres["#{genre.name}"][:ids])

    publisher_books = Book.where(publisher: publisher).
    where.not(id: publishers["#{publisher.name}"][:ids])

    max_arr = [author_books.length, genre_books.length, publisher_books.length]
    max_index = max_arr.index(max_arr.max)
    if max_index == 0
      current_user.update_columns(recomendation: author.name, recomendation_type: 'author')
    elsif max_index == 1
      current_user.update_columns(recomendation: genre.name, recomendation_type: 'genre')
    else
      current_user.update_columns(recomendation: publisher.name, recomendation_type: 'publisher')   
    end  
    return max_index == 0 ? author_books : max_arr == 1 ? genre_books : publisher_books
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSearchEngine</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <%= yield %>
  </body>
</html>

app/views/search/_book.html.erb
<aside>
<p>title: <%=book.title%><p>
<p>content: <%=book.content[1..100]%><p>
</aside>

app/views/search/_recomendation.html.erb
<aside>
<p>title: <%=recomendation.title%><p>
<p>content: <%=recomendation.content%><p>
</aside>

app/views/search/_recomendations.html.erb
<%if recomendations.nil? == false %>
<hr class="w-[80%] mx-auto h-1 bg-black"/>
<h2>Recomendations:</h2>
<% recomendations.each do |recomendation| %>
  <%=render 'recomendation', recomendation: recomendation %>
<%end%>
<%end%>

app/views/search/_results.html.erb
<%if books.nil? == false %>
<h2>Results:</h2>
<% books.each do |book| %>
  <%=render 'book', book: book %>
<%end%>
<%end%>

app/views/search/_search.html.erb
<%=form_with(url: search_index_path,  method: :post, class: "flex flex-col gap-3 w-48 h-fit mb-3 mt-7 mx-auto",
data: { controller: "search", action: "keyup->search#searchProcess", request_url: search_url }) do |f| %> 
   <%= f.text_field :text, class: 'p-1 focus:placeholder-white rounded-2xl',
   placeholder: 'search books', data: { search_target: 'input' } %>
<%end%>

app/views/search/index.html.erb
<%=render 'search'%>
<section id='books' class='m-2'>
<%=render 'results', books: @books %>
</section>
<section id='recomendations' class='m-2 mt-5'>
<%=render 'recomendations', recomendations: @recomendations %>
</section>